# Generated by Django 5.2.6 on 2025-10-01 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_personaje_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='habilidad1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seleccion1', to='core.habilidad'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='habilidad2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seleccion2', to='core.habilidad'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='opcion_hab1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opcion1', to='core.habilidad'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='opcion_hab2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opcion2', to='core.habilidad'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='opcion_hab3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opcion3', to='core.habilidad'),
        ),
    ]
